use anyhow::Error;

#[tokio::main]
async fn main() -> Result<(), Error> {
    println!("Hello, world!");

    Ok(())
}
